insert into equipo values('e12','Arqueria','879');
insert into equipo values('e13','Balone Basquet','234');
insert into equipo values('e14','Pesas','982');
insert into equipo values('e15','Espadas','867');
insert into equipo values('e16','Bandas','675');
insert into equipo values('e17','Pelotas','193');
insert into equipo values('e18','Raquetas','536');
insert into equipo values('e19','Sillas Montar','938');
insert into equipo values('e20','Guayos','765');
insert into equipo values('e01','Gorros banio','987');
insert into equipo values('e02','Toallas','123');
insert into equipo values('e03','Balon Futbol','124');
insert into equipo values('e04','Barras','876');
insert into equipo values('e05','Mallas','654');
insert into equipo values('e06','Canchitas','649');
insert into equipo values('e07','Bicicleta','917');
insert into equipo values('e08','Triciclos','242');
insert into equipo values('e09','Tablero y fichas Ajedrez','657');
insert into equipo values('e10','Raqueta squad','879');
insert into equipo values('e11','Obsaculos','452');